export const zzc_zuche_city_tbl = {
    "id" : { type: 'string', unique: true },
    "name" : String,
    "code" : String,
    "lat" : String,
    "lng" : String,
    "alphabet" : String,
    "rank" : String,
    "hot" : String,
    "old_w_city_id" : String,
    "coordinate_id" : String,
    "created_at" : String,
    "updated_at" : String,
    "deleted_at" : String,
    "province_code" : String,
    "en_name" : String,
    "is_capital" : String,
    "valid" : String,
    "w_city_id" : String,
    "p_w_city_id" : String
};